# Generated by Django 5.2 on 2025-07-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='reserva_hora_apertura_pasado',
            field=models.TimeField(default='08:00', help_text='Hora apertura reservas para pasado mañana'),
        ),
        migrations.AddField(
            model_name='community',
            name='reserva_max_dias',
            field=models.PositiveIntegerField(default=2, help_text='Máximo días vista (0=hoy, 1=mañana, 2=pasado mañana)'),
        ),
        migrations.AddField(
            model_name='court',
            name='reserva_hora_apertura_pasado',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='reserva_max_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
