# Generated by Django 5.2 on 2025-05-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("court", "timeslot", "date"), name="unique_reservation"
            ),
        ),
    ]
