# Generated by Django 5.2 on 2025-05-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservationinvitation",
            unique_together={("reserva", "email")},
        ),
        migrations.AddField(
            model_name="reservationinvitation",
            name="nombre_invitado",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nombre del invitado",
            ),
        ),
    ]
