# Generated by Django 5.2 on 2025-07-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_community_reserva_hora_apertura_pasado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='nombre'),
        ),
    ]
