# Generated by Django 5.2 on 2025-05-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_invitadoexterno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reservations.community",
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
