# Generated by Django 5.2 on 2025-07-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_usuario_accepted_terms_usuario_terms_accepted_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationinvitation',
            unique_together={('reserva', 'email', 'nombre_invitado')},
        ),
    ]
