# Generated by Django 5.2 on 2025-06-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_usuario_community_alter_community_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="estado",
            field=models.CharField(
                choices=[("activa", "Activa"), ("cancelada", "Cancelada")],
                default="activa",
                max_length=20,
            ),
        ),
    ]
