# Generated by Django 5.2 on 2025-07-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservationinvitation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitadoexterno',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invitadoexterno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='invitadoexterno',
            unique_together={('usuario', 'email', 'nombre')},
        ),
    ]
