# Generated by Django 5.2 on 2025-07-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_invitadoexterno_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationinvitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
