# Generated by Django 5.2 on 2025-06-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_alter_reservationcancelada_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vivienda",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viviendas",
                to="reservations.community",
            ),
        ),
    ]
