# Generated by Django 5.2 on 2025-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0010_remove_reservation_unique_reservation_per_court_timeslot_date_and_more",
        ),
    ]

    operations = [
      
        migrations.AddField(
            model_name="community",
            name="code",
            field=models.CharField(
                default=291301,
                help_text="Código de registro de la comunidad",
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
